### ISSUE TITLE
Custom error prone checks

### ISSUE THREAD

**Issue by tom-smalls** [tbroyer/gradle-errorprone-plugin-v0.0.x#23]
Hi,

Error Prone supports the writing of your own checks within your own code base (see https://groups.google.com/d/msg/error-prone-discuss/WL-mNWt3R9M/kVzr_mGtZ44J). Does the Gradle error prone plugin support this feature? I've had success in the past with custom checks using BUCK with Error Prone, but haven't been able to get them to run using Gradle yet.

Thanks,

**Comment by tbroyer** [comment]
Actually, AFAICT, Error Prone requires you to fork the code in order to add your own checks. If you do that, then yes the plugin supports using your own forked version of Error Prone (see the README for how to do that).

**Comment by tom-smalls** [comment]
This functionality was added in 2014 (see https://github.com/google/error-prone/commit/53969f2f893737d8b0b5fa39482566f72024d514), and was later refactored to be in the ErrorProneScanner (https://github.com/google/error-prone/blob/4a5b4c403e6780f190a313657613d0b5e846950c/core/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java#L158)

**Comment by tbroyer** [comment]
Ah yes, sorry, what I (think I) actually meant is that there's no agreed-upon way to plug/configure/discover your own checks without changing the way you bootstrap Error Prone. The way the plugin works is simply to call `new ErrorProneCompiler.Builder().build().compile(args)`, like most other integrations, as suggested by the Error Prone documentation.

I think I could do something similar to [what Bazel does](https://github.com/bazelbuild/bazel/blob/4ab4f05a8cbbaa4b7d938d1d305961fe95a5416c/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/errorprone/ErrorPronePlugin.java#L136-L147) but I'd rather wait for it to be moved to Error Prone proper, as suggested by the TODO comment in there.

This should probably be discussed on the Error Prone mailing list first, to get an idea of when (and if) it'll be available in Error Prone proper, and/or if we should do things in each build tool integration, possibly specific to the build tool (for instance, for Gradle, use a specific `configuration` where you'd declare your checker dependencies, rather than relying on the processor path like Bazel does).

**Comment by tom-smalls** [comment]
That's a good idea, thanks for getting back to me.

**Comment by tbroyer** [comment]
Now waiting for Error Prone 2.0.10 ;-)

**Comment by tom-smalls** [comment]
I saw; really impressed about how it was all just.....done!

**Comment by tom-smalls** [comment]
Error Prone 2.0.11 was been released. Is there any work outstanding to be able to load custom checks for the gradle plugin?

**Comment by tbroyer** [comment]
No. You just need to put your custom checks in the `-processorpath`. You can either configure this yourself:

```
configurations {
  apt
}
dependencies {
  apt your_custom_checks
}
tasks.withType(JavaCompile)*.options.compilerArgs += [ '-processorargs', configurations.apt.asPath ]
```

or use the gradle-apt-plugin or android-apt plugins (or the new Android plugin for Gradle with Jack & Jill)
