### ISSUE TITLE
Add task to run manually

### ISSUE THREAD

**Issue by jaredsburrows** [tbroyer/gradle-errorprone-plugin-v0.0.x#28]
Is there currently a way to run this via a task? I do not want to run this on each `assemble` task.

**Comment by tbroyer** [comment]
Error Prone is an enhanced JavaC, and this plugin _enhances_ `JavaCompile` tasks in to use Error Prone as the compiler. If you want to conditionally use Error Prone, then either conditionally enhance the tasks (based on a Gradle property for example) or create new tasks. See https://github.com/tbroyer/gradle-errorprone-plugin#advanced-usage for this kind of advanced usage where you don't want the plugin to automatically enhance all `JavaCompile` tasks.

You could, for example (untested!), do something like:

``` gradle
ext.withErrorprone = project.hasProperty("withErrorprone") && Boolean.parseBoolean(project.property("withErrorprone")));
ext.errorproneToolchain = ErrorProneToolChain.create(project)
tasks.withType(JavaCompile).all {
  inputs.property("withErrorprone", withErrorprone)
  if (withErrorprone) {
    toolChain errorproneToolchain
  }
}
```

So that calling your build with `-PwithErrorprone=true` would _turn on_ Error Prone, without without the `-PwithErrorprone` or with `-PwithErrorprone=false` would use the standard Java compiler.

That being said, I don't quite understand why you would want to do that…

**Comment by jaredsburrows** [comment]
@tbroyer This is exactly what I wanted! I just wanted a way to toggle this gradle plugin on or off on javac tasks. Thank you!

**Comment by jaredsburrows** [comment]
@tbroyer Here is what I did:

// from errorprone.gradle

```
apply plugin: "net.ltgt.errorprone"

tasks.withType(JavaCompile) {
    configure(options) {
        // Apply custom errorprone rules
        compilerArgs << "-Xep:LongLiteralLowerCaseSuffix:WARN"
    }
}

configurations.errorprone {
    // 2.0.5 is the last version compatible with JDK 7
    resolutionStrategy.force "com.google.errorprone:error_prone_core:2.0.5"
}
```

Then:

`if (condition) { apply from: file("gradle/errorprone.gradle") }`
