### ISSUE TITLE
How can I Turn on experimental BugPatterns?

### ISSUE THREAD

**Issue by yogurtearl** [tbroyer/gradle-errorprone-plugin-v0.0.x#3]
In the gradle plugin, how can I enable all the patterns described here:

https://code.google.com/p/error-prone/wiki/BugPatterns

**Comment by tbroyer** [comment]
Hmm, how do you do it _without_ the gradle plugin? :smiley:

**Comment by yogurtearl** [comment]
Not sure, I just started using error-prone and didn't find anything on the google code site... :)

**Comment by tbroyer** [comment]
Closing for now, as I don't think it's (easily) doable. Please reopen after you ask for guidance on the error prone forum and have an idea how it could be done (both technically, and what the DSL could look like). Let's consider this a "not planned" feature for now.

**Comment by alexeagle** [comment]
Tom - if you'd like to enable it, it's pretty easy. Looks like you already have a org.gradle.api.artifacts.Configuration where you could add something like "enable_experimental:boolean"
Then you'd use it before you call build() on the ErrorProneCompiler.Builder
https://github.com/tbroyer/gradle-errorprone-plugin/blob/master/src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java#L84

in particular, you'd want something like
builder.report(new ErrorProneScanner(new EnabledPredicate() {
      @Override
      public boolean isEnabled(Class<? extends BugChecker> checkerClass, BugPattern annotation) {
        return true;
      }
    }))

At a minimum it seems like we should have ErrorProneScanner.EnabledPredicate.ALL_CHECKS next to the existing ErrorProneScanner.EnabledPredicate.DEFAULT_CHECKS so you could just do
report(new ErrorProneScanner(ALL_CHECKS))

**Comment by tbroyer** [comment]
The problem is that we're currently using an API that's just deprecated and will be removed in the next Gradle version.

As I understand it, we should be able to use the JavaCompiler API by then, but then we cannot use the builder, right? (I must admit I haven't yet looked at the JavaCompiler implementation).

See http://issues.gradle.org/browse/GRADLE-3085

**Comment by tbroyer** [comment]
FYI, the plugin no longer works with Gradle 2.0-rc-1 which removed the hook we used.

I'm [volunteering to fixing GRADLE-3085](http://gradle.markmail.org/thread/kmwvozu5cyljdqqo) to add support arbitrary `javax.tools.JavaCompiler`, hoping it can be ready for Gradle 2.0. Otherwise, the plugin would have to fallback to forking a JVM and calling ErrorProne's `main()`.

Re. experimental bug patterns, that means `ErrorProneOptions` should eventually handle an `-Xepexperimental` or similar option.
