### ISSUE TITLE
Add DSL for filtering classes

### ISSUE THREAD

**Issue by rafaeltoledo** [tbroyer/gradle-errorprone-plugin-v0.0.x#36]
Some of the warnings reported by error prone (on Android) usually is done by generated classes from Dagger, DataBinding, and others. Would be great to have such option to filter classes from the plugin. Something like:

```groovy
errorprone {
  excludeClasses = ['**/Dagger*.*', '**/*Binding.*']
}
```

**Comment by jbduncan** [comment]
For generated classes, it's actually rather easy to filter them out (assuming they're annotated with `@Generated`). Just simply write the following in your build script.

```gradle
tasks.withType(JavaCompile) {
  options.compilerArgs += [
    // See: https://github.com/google/error-prone/issues/329
    '-XepDisableWarningsInGeneratedCode'
  ]
}
```

**Comment by rafaeltoledo** [comment]
This works for some classes, but not for Databinding (the bigger source of warning on my current project)

**Comment by tbroyer** [comment]
This plugin is **only** for enabling Error Prone in Gradle `JavaCompile` tasks; there's willfully no DSL because there's no real need for it (`tasks.withType(JavaCompile) { options.compilerArgs … }` is simple enough).

Wrt what you're asking for specifically: Error Prone doesn't provide such exclusions, so the compilation would have to be done in stages: first what the generated code will depend on (with Error Prone), then the generated code (without Error Prone), and finally what depends on the generated (with Error Prone). This is of course only possible if there are no dependency cycles between those stages, and it's nearly impossible to determine what should go in each stage automatically. So if you really want it, you'll have to configure 3 compilation tasks, possibly using 3 source sets with appropriate inclusions/exclusions; but AFAICT Android-Gradle projects are mostly "black boxes" and databinding has no public API for integrating it into non-Android-Gradle projects (uses 3 Gradle tasks and an annotation processor).

In any case, you should ask:
 * the Android Databinding team to generate code that compiles with Error Prone, or at least have `@Generated` annotations (as an option, as `@Generated` isn't included in the Android "profile" of the Java runtime library) so that `-XepDisableWarningsInGeneratedCode` filters them out;
 * the Android-Gradle team to support using Error Prone (this is unlikely as they seem to be moving to Jack);
 * the Error Prone team to support such exclusions

_Disclaimer:_ I don't do Android development, I only dug a bit into the Android databinding library and Gradle plugin code.
