### ISSUE TITLE
Gradle 3.5 support

### ISSUE THREAD

**Issue by ben-manes** [tbroyer/gradle-errorprone-plugin-v0.0.x#37]
It appears that RC1 breaks...

```
Caused by: java.lang.UnsupportedOperationException
        at org.gradle.api.tasks.compile.JavaCompile.setToolChain(JavaCompile.java:141)
        at org.gradle.api.tasks.compile.JavaCompile_Decorated.setToolChain(Unknown Source)
        at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:20)
        at net.ltgt.gradle.errorprone.ErrorPronePlugin$1.execute(ErrorPronePlugin.java:17)
```

**Comment by wolfs** [comment]
Thank you for your report.
Now that we detect the toolchain from fork options and do not allow to set the toolchain manually I see why the plugin fails.
Note that even fixing the possibility to set the toolchain I am pretty sure the plugin will fail afterwards since we changed then interface of `JavaToolChain` and `JavaToolChainInternal`, which are both not part of the public API.
If we re-add the possibility to set the Java tool chain manually on `JavaCompile`, would you adjust the plugin to implement the new types? It would still be somewhat brittle since it is possible that we change those internal interfaces again in the not so distant future.

**Comment by wolfs** [comment]
@tbroyer @ben-manes I opened an issue for Gradle, could we continue the discussion over there: https://github.com/gradle/gradle/issues/1645

**Comment by tbroyer** [comment]
Changes tested with 3.6-20170325000056+0000. I'll uncomment the `@Override` when 3.5-rc-2 or 3.5 is released (and I'll start building with those).

**Comment by ben-manes** [comment]
Unfortunately rc-2 doesn't work for me. Do I require the changes on master?

```
* What went wrong:
net.ltgt.gradle.errorprone.ErrorProneToolChain.getVersion()Ljava/lang/String;
```

**Comment by tbroyer** [comment]
> Do I require the changes on master?

Yes; try using https://jitpack.io/#tbroyer/gradle-errorprone-plugin/master-SNAPSHOT

I'll release v0.0.10 once Gradle 3.5 is out.

**Comment by tbroyer** [comment]
I just updated the build to use 3.5-rc-2 in 0c76d1a130f821e9767a95760741a38dde0e9e0d, and it uses
```gradle
classpath "com.github.tbroyer:gradle-errorprone-plugin:052a7aedb2"
```
to get a compatible build from the previous changes to apply to itself.

**Comment by vanniktech** [comment]
Gradle 3.5 was released.

**Comment by tbroyer** [comment]
Aaaand v0.0.10 has just been released!

(thanks for the ping on Gradle 3.5, as it hasn't been announced yet AFAICT)

**Comment by vanniktech** [comment]
That was fast, thanks. [Here are the release notes](https://docs.gradle.org/current/release-notes.html)

**Comment by ben-manes** [comment]
Thanks! I think you forgot to update the readme

**Comment by tbroyer** [comment]
Thanks, readme updated, and build now uses 0.0.10 too.
