### ISSUE TITLE
Using `kapt` seems to prevent arguments from being passed to ErrorProne

### ISSUE THREAD

**Issue by magneticflux-** [tbroyer/gradle-errorprone-plugin-v0.0.x#55]
Before I changed from the normal `annotationProcessor` configuration to `kotlin-kapt`, I could pass the `-XepDisableWarningsInGeneratedCode` flag to the compiler through this:
```Gradle
tasks.withType(JavaCompile) {
    options.compilerArgs += ['-XepDisableWarningsInGeneratedCode']
}
```

After switching to the `kapt` configuration though, my flags don't get passed through and I see
```
w: Flag is not supported by this version of the compiler: -XepDisableWarningsInGeneratedCode
```
in my Gradle build log.

Am I not targeting the correct task? I also added
```Gradle
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
    kotlinOptions.freeCompilerArgs += ['-XepDisableWarningsInGeneratedCode']
}
```
but that only added another log warning identical to the first.

**Comment by tbroyer** [comment]
Can you run Gradle with `--info` and look for `Compiling with error-prone compiler` in the output? See which task it's associated to. If it's not there, then the task is not using Error Prone.

If you have a small project on GitHub I could play with that exhibits the problem, I could have a look at it too.

Finally, Error Prone is only applied to `JavaCompile` tasks, not `KotlinCompile` (it wouldn't be possible anyway).

**Comment by magneticflux-** [comment]
Here's a clean log with errors: [build.log](https://github.com/tbroyer/gradle-errorprone-plugin/files/1472247/build.log)
Here's a small project that demonstrates the issue: [ErrorProneKaptBug.zip](https://github.com/tbroyer/gradle-errorprone-plugin/files/1472248/ErrorProneKaptBug.zip)

I see the `Compiling with error-prone compiler` message just before it prints errors that should have been suppressed.

**Comment by tbroyer** [comment]
If I run that project with `--debug` (`./gradlew --debug :app:compileDebugJavaWithJavac`), I can see that `-XepDisableWarningsInGeneratedCode` is properly passed to Error Prone.

The generated code (`app/build/generated/source/kapt/debug/com/github/magneticflux/errorpronekaptbug/AppDatabase_Impl.java` for instance) is not annotated with `@Generated` though, so Error-Prone does not treat it as a generated file, and `-XepDisableWarningsInGeneratedCode` does not apply.

Adding a dependency that brings `javax.annotation.Generated` in (the problem being that the Android API does not have `javax.annotation`, contrary to the JDK) fixes the problem:
```gradle
implementation 'javax.annotation:jsr250-api:1.0'
```

**Comment by magneticflux-** [comment]
It's odd that `kapt` would cause the compile classpath to change since everything was working with the built-in Android annotation processor. The current Room compiler also depends on `javax.annotation-api:1.2` which should include the `@Generated` annotation. [Room compiler pom](https://dl.google.com/dl/android/maven2/android/arch/persistence/room/compiler/1.0.0/compiler-1.0.0.pom)

Any idea what could cause this?

**Comment by tbroyer** [comment]
Absolutely no idea (note that I do neither Android nor Kotlin development; I actually had to install an Android dev env to debug your repro case).

Note that the `javax.annotation-api` needs to be in the classpath (`compileOnly`, `api` or `implementation`), not in the processorpath (`annotationProcessor` or `kapt`); so the dependency from the Room compiler doesn't really matter (also, it's in `test` scope anyway, so wouldn't apply).

But keep in mind that if you want to use `-XepDisableWarningsInGeneratedCode`, you need to make sure you have `javax.annotation.Generated` in the classpath (otherwise, generated code annotated with it wouldn't compile; which is why some annotation processors conditionally generate the `@Generated` annotation depending on its presence in the classpath, and incidentally this is the reason I know about the issue, not doing Android dev myself but having seen bugs reported to [Dagger](https://github.com/google/dagger/issues/95), [AutoValue](https://github.com/google/auto/issues/240), etc.), so it would be a good idea to add an explicit dependency to it, whether other dependencies bring it transitively or not.

**Comment by magneticflux-** [comment]
Thanks, that makes sense! I still don't quite know why it only started to fail now, but it works lol. For future reference, I added `compileOnly 'javax.annotation:javax.annotation-api:1.3.1'` to my dependencies block and it compiles correctly with no spurious warnings.
