### ISSUE TITLE
Automated releases of gradle-errorprone-plugin

### ISSUE THREAD

**Issue by mockitoguy** [tbroyer/gradle-errorprone-plugin-v0.0.x#61]
Hey!

Are you interested in setting up automated releases for gradle-errorprone-plugin on every pull request? I'm reaching out on behalf of https://github.com/mockito/shipkit team - we built an OSS Gradle Plugin that nicely streamlines releasing, creates release notes, bumps versions, and more.

Let us know!

**Comment by tbroyer** [comment]
Hi,

Thanks for the suggestion, but I'm not interested I'm afraid. Reasons include:
 * I deploy to the Plugin Portal, snapshots still can be obtained from [JitPack](https://jitpack.io/#tbroyer/gradle-errorprone-plugin)
 * I hate automated commits polluting the log (which means I probably won't use it for other projects either), and have come to prefer keeping track of release versions only in git tags (this project still has release commits to update the README, but this is only a artifact of keeping the compatibility grid in the Git repo rather than in, say, the wiki)

Wrt release notes, I just spent some time filling them out in https://github.com/tbroyer/gradle-errorprone-plugin/releases. I also created [milestones](https://github.com/tbroyer/gradle-errorprone-plugin/milestones?state=closed) and linked the related issues. Finally, I added appropriate labels to all other closed issues, so closed issues should either have a label or a milestone. It took me some time to clean this up, but it won't ask me much to keep it in a clean state in the future.
